CREATE TABLE IF NOT EXISTS app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  name VARCHAR(160) NOT NULL,
  role VARCHAR(30) NOT NULL CHECK (role IN ('Biblioteca', 'Diretor')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_sessions (
  token_hash CHAR(64) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_app_sessions_expires_at ON app_sessions(expires_at);

CREATE TABLE IF NOT EXISTS readers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_code VARCHAR(64) NOT NULL,
  name VARCHAR(200) NOT NULL DEFAULT '',
  reader_type VARCHAR(100) NOT NULL DEFAULT '',
  class_sector VARCHAR(120) NOT NULL DEFAULT '',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Os IDs visuais dos leitores são numéricos, derivados do ID técnico e não mudam
-- quando tipo, turma ou setor são editados. A recriação do índice também migra
-- com segurança os códigos antigos como ALU-0001 e PROF-0001.
DROP INDEX IF EXISTS uq_readers_registration;
UPDATE readers
SET registration_code = LPAD(id::TEXT, GREATEST(4, LENGTH(id::TEXT)), '0')
WHERE registration_code <> LPAD(id::TEXT, GREATEST(4, LENGTH(id::TEXT)), '0');
CREATE UNIQUE INDEX uq_readers_registration ON readers(LOWER(registration_code));

CREATE TABLE IF NOT EXISTS books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  isbn VARCHAR(40) NOT NULL DEFAULT '',
  title VARCHAR(260) NOT NULL DEFAULT '',
  author VARCHAR(220) NOT NULL DEFAULT '',
  publisher VARCHAR(180) NOT NULL DEFAULT '',
  publication_year VARCHAR(12) NOT NULL DEFAULT '',
  category VARCHAR(100) NOT NULL DEFAULT '',
  location VARCHAR(160) NOT NULL DEFAULT '',
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1),
  available INTEGER NOT NULL DEFAULT 1 CHECK (available >= 0 AND available <= quantity),
  book_condition VARCHAR(100) NOT NULL DEFAULT '',
  lost_copies INTEGER NOT NULL DEFAULT 0 CHECK (lost_copies >= 0 AND lost_copies <= quantity),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Assim como nos leitores, o ID visual de cada livro é numérico, permanente e
-- derivado do ID técnico. Este trecho também migra códigos antigos como LIV-0001.
DROP INDEX IF EXISTS uq_books_code;
UPDATE books
SET code = LPAD(id::TEXT, GREATEST(4, LENGTH(id::TEXT)), '0')
WHERE code <> LPAD(id::TEXT, GREATEST(4, LENGTH(id::TEXT)), '0');
CREATE UNIQUE INDEX uq_books_code ON books(LOWER(code));
CREATE UNIQUE INDEX IF NOT EXISTS uq_books_isbn_active
  ON books(isbn) WHERE deleted_at IS NULL AND isbn <> '';

CREATE TABLE IF NOT EXISTS legacy_book_imports (
  source VARCHAR(120) NOT NULL,
  legacy_book_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL REFERENCES books(id),
  imported_quantity INTEGER NOT NULL CHECK (imported_quantity >= 1),
  imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (source, legacy_book_id)
);

CREATE INDEX IF NOT EXISTS idx_legacy_book_imports_book
  ON legacy_book_imports(book_id);

CREATE TABLE IF NOT EXISTS loans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reader_id BIGINT NOT NULL REFERENCES readers(id),
  book_id BIGINT NOT NULL REFERENCES books(id),
  loan_date DATE NOT NULL,
  due_date DATE NOT NULL,
  return_date DATE,
  penalty_until DATE,
  responsible VARCHAR(160) NOT NULL DEFAULT '',
  return_condition VARCHAR(100),
  return_note TEXT,
  warning BOOLEAN NOT NULL DEFAULT FALSE,
  book_lost BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'ativo',
  renewals JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (jsonb_typeof(renewals) = 'array'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (due_date >= loan_date),
  CHECK (return_date IS NULL OR return_date >= loan_date),
  CONSTRAINT loans_status_check CHECK (status IN ('ativo', 'devolvido', 'perdido', 'atrasado'))
);

-- Migra bancos criados antes da inclusao do status explicito.
ALTER TABLE loans
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ativo';

CREATE OR REPLACE FUNCTION calculate_loan_status(
  loan_return_date DATE,
  loan_book_lost BOOLEAN,
  loan_due_date DATE
)
RETURNS VARCHAR(20)
LANGUAGE SQL
STABLE
AS $$
  SELECT CASE
    WHEN COALESCE(loan_book_lost, FALSE) THEN 'perdido'
    WHEN loan_return_date IS NOT NULL THEN 'devolvido'
    WHEN loan_due_date < CURRENT_DATE THEN 'atrasado'
    ELSE 'ativo'
  END::VARCHAR(20);
$$;

UPDATE loans
SET status = calculate_loan_status(return_date, book_lost, due_date);

ALTER TABLE loans DROP CONSTRAINT IF EXISTS loans_status_check;
ALTER TABLE loans
  ADD CONSTRAINT loans_status_check
  CHECK (status IN ('ativo', 'devolvido', 'perdido', 'atrasado'));

CREATE OR REPLACE FUNCTION set_loan_status()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.status := calculate_loan_status(NEW.return_date, NEW.book_lost, NEW.due_date);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_loans_sync_status ON loans;
CREATE TRIGGER trg_loans_sync_status
BEFORE INSERT OR UPDATE OF return_date, book_lost, due_date, status ON loans
FOR EACH ROW
EXECUTE FUNCTION set_loan_status();

-- Triggers nao sao executados apenas pela passagem do tempo. A API chama esta
-- funcao antes de consultar estados para persistir emprestimos que venceram.
CREATE OR REPLACE FUNCTION refresh_loan_statuses()
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
  affected_rows INTEGER;
BEGIN
  UPDATE loans
  SET status = calculate_loan_status(return_date, book_lost, due_date)
  WHERE status IS DISTINCT FROM calculate_loan_status(return_date, book_lost, due_date);
  GET DIAGNOSTICS affected_rows = ROW_COUNT;
  RETURN affected_rows;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_loans_reader ON loans(reader_id);
CREATE INDEX IF NOT EXISTS idx_loans_book ON loans(book_id);
CREATE INDEX IF NOT EXISTS idx_loans_status ON loans(status);
DROP INDEX IF EXISTS idx_loans_active_due;
CREATE INDEX idx_loans_active_due
  ON loans(due_date) WHERE status IN ('ativo', 'atrasado');

CREATE TABLE IF NOT EXISTS reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id BIGINT NOT NULL REFERENCES books(id),
  reader_id BIGINT NOT NULL REFERENCES readers(id),
  reservation_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'ativa' CHECK (status IN ('ativa', 'atendida', 'cancelada')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reservations_queue
  ON reservations(book_id, id) WHERE status = 'ativa';
CREATE UNIQUE INDEX IF NOT EXISTS uq_reservation_reader_book_active
  ON reservations(book_id, reader_id) WHERE status = 'ativa';
